baseURL: "https://evancurtin.com/"
languageCode: "en-us"
title: "Evan's Blog"
description: Hi
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true

params:
  author: "Evan Curtin"
  description: " "
  
  social:
    - name: github
      url: https://github.com/ecurtin2
    - name: linkedin
      url: https://www.linkedin.com/in/evanmcurtin/
